FROM node:15-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apk add --no-cache protoc

COPY web-client/* /usr/src/app/
COPY protobufs /usr/src/app/

RUN npm ci 

RUN protoc --plugin=./node_modules/.bin/protoc-gen-ts --ts_out ./generated --proto_path ./protobufs ./protobufs/*.proto

RUN npm run build

EXPOSE 3000
CMD [ "npm", "start" ]