FROM node:15-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apk add --no-cache protoc

COPY next-app /usr/src/app
COPY protobufs /usr/src/app/protobufs

RUN npm ci 

RUN protoc --plugin=./node_modules/.bin/protoc-gen-ts --ts_out ./generated --proto_path ./protobufs ./protobufs/*.proto

RUN npm run build

EXPOSE $PORT
CMD npx next start -p $PORT