FROM python:3.7-alpine
RUN mkdir /app
WORKDIR /app

RUN apk add --no-cache protoc

RUN pip install poetry
RUN poetry config settings.virtualenvs.create false

COPY server /app
COPY protobufs /app/protobufs

RUN poetry install
RUN protoc --python_out=./generated --twirpy_out=./generated --proto_path=../protobufs ../protobufs/*.proto

EXPOSE 3001
CMD [ "poetry ", "run", "uvicorn", "server:app", "--port=3001" ]