FROM python:3.9-alpine
RUN mkdir /app
WORKDIR /app

RUN apk add --no-cache protoc gcc build-base libffi-dev openssl-dev

RUN pip install poetry
RUN poetry config virtualenvs.create false --local

COPY server /app
COPY protobufs /app/protobufs

RUN poetry install
RUN protoc --python_out=./generated --twirpy_out=./generated --proto_path=../protobufs ../protobufs/*.proto

EXPOSE 3001
CMD [ "poetry ", "run", "uvicorn", "server:app", "--port=3001" ]