version: 2.1

workflows:
  build-and-deploy: 
    jobs:
      - build-next-app
      - build-twirp-app

jobs:
  build-next-app:  
    docker:
      - image: docker
    environment:
      PORT: 3000
    steps:
      - setup_remote_docker
      - checkout
      - run: cd next-app && docker build -t next-twirp-test-next --build-arg NEXT_PUBLIC_TWIRP_ENDPOINT='https://next-twirp-test-twirp-app.herokuapp.com/rpc' .

  build-twirp-app:  
    docker:
      - image: docker
    environment:
      PORT: 3001
    steps:
      - setup_remote_docker
      - checkout
      - run: cd twirp-app && docker build -t next-twirp-test-twirp .