version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4

workflows:
  build-and-deploy: 
    jobs:
      - build-next-app
      - build-twirp-app

jobs:
  build-next-app:  
    docker:
      - image: cimg/base:2020.01
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run: 
          environment:
            NEXT_PUBLIC_TWIRP_ENDPOINT: https://next-twirp-test-twirp-app.herokuapp.com/rpc
          command: |
            cd next-app
            echo $PORT
            docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
            docker build -t registry.heroku.com/next-twirp-test-next-app/web --build-arg NEXT_PUBLIC_TWIRP_ENDPOINT .
            docker push registry.heroku.com/next-twirp-test-next-app/web
            heroku container:release web

  build-twirp-app:  
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 
          command:
            cd twirp-app
            docker build -t next-twirp-test-twirp .