version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4
  docker: circleci/docker@1.5.0

workflows:
  build-and-deploy: 
    jobs:
      - build-next-app
      - build-twirp-app

jobs:
  build-next-app:  
    docker:
      - image: cimg/base:2020.01
    steps:
      - docker/install-docker-tools
      - setup_remote_docker
      - checkout
      - run: 
          command: |
            sudo apt install docker.io
            cd next-app
            export PORT=3000
            docker build -t next-twirp-test-next --build-arg NEXT_PUBLIC_TWIRP_ENDPOINT='https://next-twirp-test-twirp-app.herokuapp.com/rpc' .
      - heroku/install
      - heroku/push-docker-image:
          app-name: next-twirp-test-next-app
          process-types: web
      - heroku/release-docker-image:
          app-name: next-twirp-test-next-app
          process-types: web

  build-twirp-app:  
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 
          command:
            cd twirp-app
            export PORT=3001
            docker build -t next-twirp-test-twirp .