version: 2.1

workflows:
  build-and-deploy: 
    jobs:
      - build-next-app
      - build-twirp-app

jobs:
  build-next-app:  
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 
        - name: Build next docker image
        - command: |
          cd next-app
          export PORT=3000
          docker build -t next-twirp-test-next --build-arg NEXT_PUBLIC_TWIRP_ENDPOINT='https://next-twirp-test-twirp-app.herokuapp.com/rpc' .

  build-twirp-app:  
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 
        - name: Build twirp docker image
        - command: |
          cd twirp-app
          export PORT=3001
          docker build -t next-twirp-test-twirp .