version: 2.1

workflows:
  build-and-deploy: 
    jobs:
      - build-next-app
      - build-twirp-app

jobs:
  build-next-app:  
    docker:
      - image: docker
    steps:
      - checkout
      - run: cd next-app && docker build -t next-twirp-test-next .

  build-twirp-app:  
    docker:
      - image: docker
    steps:
      - checkout
      - run: cd twirp-app && docker build -t next-twirp-test-twirp .